export default {
  ADD_TODO_START: 'ADD_TODO_START',
  ADD_TODO_OK: 'ADD_TODO_OK',
  ADD_TODO_ERROR: 'ADD_TODO_ERROR',

  GET_ALL_TODOS_START: 'GET_ALL_TODOS_START',
  GET_ALL_TODOS_OK: 'GET_ALL_TODOS_OK',
  GET_ALL_TODOS_ERROR: 'GET_ALL_TODOS_ERROR',
};
