export default {
  ADD_TODO_START: 'ADD_TODO_START',
  ADD_TODO_OK: 'ADD_TODO_OK',
  ADD_TODO_ERROR: 'ADD_TODO_ERROR',

  GET_ALL_TODOS_START: 'GET_ALL_TODOS_START',
  GET_ALL_TODOS_OK: 'GET_ALL_TODOS_OK',
  GET_ALL_TODOS_ERROR: 'GET_ALL_TODOS_ERROR',

  REMOVE_TODO_START: 'REMOVE_TODO_START',
  REMOVE_TODO_OK: 'REMOVE_TODO_OK',
  REMOVE_TODO_ERROR: 'REMOVE_TODO_ERROR',

  UPDATE_TODO_START: 'UPDATE_TODO_START',
  UPDATE_TODO_OK: 'UPDATE_TODO_OK',
  UPDATE_TODO_ERROR: 'UPDATE_TODO_ERROR',

  REMOVE_MANY_START: 'REMOVE_MANY_START',
  REMOVE_MANY_OK: 'REMOVE_MANY_OK',
  REMOVE_MANY_ERROR: 'REMOVE_MANY_ERROR',
};
