export default {
  ADD_TODO_START: 'ADD_TODO_START',
  ADD_TODO_OK: 'ADD_TODO_OK',
  ADD_TODO_ERROR: 'ADD_TODO_ERROR',

  GET_ALL_TODO_START: 'GET_ALL_TODO_START',
  GET_ALL_TODO_OK: 'GET_ALL_TODO_OK',
  GET_ALL_TODO_ERROR: 'GET_ALL_TODO_ERROR',
};
